export const GENDER_SELECTION = "GENDER_SELECTION";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const RETURN_TO_FIRST_PAGE = "RETURN_TO_FIRST_PAGE";

export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const CHANGE_QUESTION_PAGE = "CHANGE_QUESTION_PAGE";
export const RETURN_TO_PREVIUS_QUESTION = "RETURN_TO_PREVIUS_QUESTION";
export const CLICKED_ON_NEXT_BUTTON = "CLICKED_ON_NEXT_BUTTON";
export const ON_SCALE_CHANGE = "ON_SCALE_CHANGE";
export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
export const GO_TO_CALENDAR = "GO_TO_CALENDAR";
export const SAVE_FETCHED_DATA = "SAVE_FETCHED_DATA";

export const NULL_ANSWER_INDEX = "NULL_ANSWER_INDEX";

export const CHOOSE_PLAN = "CHOOSE_PLAN";
